//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 2015.11.05. 13:41:53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;
using System.Web.Http.OData.Query;
using WebAPIDevExpressApp.Models;

namespace MIRTUSZContext
{

    [DatabaseAttribute(Name = "MIRTUSZ")]
    [ProviderAttribute(typeof(Devart.Data.Oracle.Linq.Provider.OracleDataProvider))]
    public partial class MIRTUSZDataContext : Devart.Data.Linq.DataContext
    {
        public static CompiledQueryCache compiledQueryCache = CompiledQueryCache.RegisterDataContext(typeof(MIRTUSZDataContext));
        private static MappingSource mappingSource = new Devart.Data.Linq.Mapping.AttributeMappingSource();

        #region Extensibility Method Definitions
    
        partial void OnCreated();
        partial void OnSubmitError(Devart.Data.Linq.SubmitErrorEventArgs args);
        partial void InsertELEMIMUNKAK(ELEMIMUNKAK instance);
        partial void UpdateELEMIMUNKAK(ELEMIMUNKAK instance);
        partial void DeleteELEMIMUNKAK(ELEMIMUNKAK instance);
        partial void InsertVELEMIMUNKAINMLIST(VELEMIMUNKAINMLIST instance);
        partial void UpdateVELEMIMUNKAINMLIST(VELEMIMUNKAINMLIST instance);
        partial void DeleteVELEMIMUNKAINMLIST(VELEMIMUNKAINMLIST instance);

        #endregion

        public MIRTUSZDataContext() :
        base(GetConnectionString("MIRTUSZDataContextConnectionString"), mappingSource)
        {
            OnCreated();
        }

        public MIRTUSZDataContext(MappingSource mappingSource) :
        base(GetConnectionString("MIRTUSZDataContextConnectionString"), mappingSource)
        {
            OnCreated();
        }

        private static string GetConnectionString(string connectionStringName)
        {
            System.Configuration.ConnectionStringSettings connectionStringSettings = System.Configuration.ConfigurationManager.ConnectionStrings[connectionStringName];
            if (connectionStringSettings == null)
                throw new InvalidOperationException("Connection string \"" + connectionStringName +"\" could not be found in the configuration file.");
            return connectionStringSettings.ConnectionString;
        }

        public MIRTUSZDataContext(string connection) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public MIRTUSZDataContext(System.Data.IDbConnection connection) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public MIRTUSZDataContext(string connection, MappingSource mappingSource) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public MIRTUSZDataContext(System.Data.IDbConnection connection, MappingSource mappingSource) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public Devart.Data.Linq.Table<ELEMIMUNKAK> ELEMIMUNKAKs
        {
            get
            {
                return this.GetTable<ELEMIMUNKAK>();
            }
        }

        public Devart.Data.Linq.Table<VELEMIMUNKAINMLIST> VELEMIMUNKAINMLISTs
        {
            get
            {
                return this.GetTable<VELEMIMUNKAINMLIST>();
            }
        }

        public Devart.Data.Linq.Table<VELEMIMUNKAINMLIST> VELEMIMUNKAINMLIST
        {
            get
            {
                return this.GetTable<VELEMIMUNKAINMLIST>();
            }
        }
    }
}

namespace MIRTUSZContext
{

    /// <summary>
    /// Elemi munkak
    /// </summary>
    [Table(Name = @"MIRTUSZ.ELEMI_MUNKAK")]
    public partial class ELEMIMUNKAK : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private long _AZONOSITO;

        private System.Nullable<System.DateTime> _TERVEZETTKEZDETIDO;

        private System.Nullable<System.DateTime> _TERVEZETTVEGIDO;

        private System.Nullable<System.DateTime> _VEGREHAJTASKEZDETIDO;

        private System.Nullable<System.DateTime> _VEGREHAJTASVEGIDO;

        private System.DateTime _FELVETELIDO;

        private System.Nullable<System.DateTime> _KIADASIDO;

        private System.Nullable<System.DateTime> _LEZARASIDO;

        private long _REGIO;

        private long _KOMUNKSTATAZONOSITO;

        private long _KANORMTEVAZONOSITO;

        private string _MEGJEGYZES;

        private System.Nullable<double> _GEOKODX;

        private System.Nullable<double> _GEOKODY;

        private string _SAPAZONOSITO;

        private System.Nullable<long> _KOZTADATAZONOSITO;

        private long _KOMPLMUNKAAZONOSITO;

        private int _SORSZAM;

        private long _KOPRIOAZONOSITO;

        private System.Nullable<long> _KORZNEVKORZET;

        private System.Nullable<long> _MIRAZONOSITO;

        private System.Nullable<long> _MIRKOMPONENS;

        private System.Nullable<double> _NORMAIDO;

        private System.Nullable<long> _KOVKANORMTEVAZONOSITO;

        private System.Nullable<long> _KOVKOPRIOAZONOSITO;

        private string _CSOATMERO;

        private string _CSOANYAG;

        private System.Nullable<long> _KESZULTSEG;

        private System.Nullable<long> _KOMKFORRASAZONOSITO;

        private System.Nullable<long> _FORRASAZONOSITO;

        private string _FORRASAZONOSITOTXT;

        private long _FELVETELFELHAZON;

        private System.Nullable<long> _KIADASFELHAZON;

        private System.Nullable<long> _LEZARASFELHAZON;

        private System.Nullable<long> _VMKIFOGASAZONOSITO;

        private System.Nullable<long> _INTEZKEDESAZON;
        #pragma warning restore 0649
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnAZONOSITOChanging(long value);
        partial void OnAZONOSITOChanged();
        partial void OnTERVEZETTKEZDETIDOChanging(System.Nullable<System.DateTime> value);
        partial void OnTERVEZETTKEZDETIDOChanged();
        partial void OnTERVEZETTVEGIDOChanging(System.Nullable<System.DateTime> value);
        partial void OnTERVEZETTVEGIDOChanged();
        partial void OnVEGREHAJTASKEZDETIDOChanging(System.Nullable<System.DateTime> value);
        partial void OnVEGREHAJTASKEZDETIDOChanged();
        partial void OnVEGREHAJTASVEGIDOChanging(System.Nullable<System.DateTime> value);
        partial void OnVEGREHAJTASVEGIDOChanged();
        partial void OnFELVETELIDOChanging(System.DateTime value);
        partial void OnFELVETELIDOChanged();
        partial void OnKIADASIDOChanging(System.Nullable<System.DateTime> value);
        partial void OnKIADASIDOChanged();
        partial void OnLEZARASIDOChanging(System.Nullable<System.DateTime> value);
        partial void OnLEZARASIDOChanged();
        partial void OnREGIOChanging(long value);
        partial void OnREGIOChanged();
        partial void OnKOMUNKSTATAZONOSITOChanging(long value);
        partial void OnKOMUNKSTATAZONOSITOChanged();
        partial void OnKANORMTEVAZONOSITOChanging(long value);
        partial void OnKANORMTEVAZONOSITOChanged();
        partial void OnMEGJEGYZESChanging(string value);
        partial void OnMEGJEGYZESChanged();
        partial void OnGEOKODXChanging(System.Nullable<double> value);
        partial void OnGEOKODXChanged();
        partial void OnGEOKODYChanging(System.Nullable<double> value);
        partial void OnGEOKODYChanged();
        partial void OnSAPAZONOSITOChanging(string value);
        partial void OnSAPAZONOSITOChanged();
        partial void OnKOZTADATAZONOSITOChanging(System.Nullable<long> value);
        partial void OnKOZTADATAZONOSITOChanged();
        partial void OnKOMPLMUNKAAZONOSITOChanging(long value);
        partial void OnKOMPLMUNKAAZONOSITOChanged();
        partial void OnSORSZAMChanging(int value);
        partial void OnSORSZAMChanged();
        partial void OnKOPRIOAZONOSITOChanging(long value);
        partial void OnKOPRIOAZONOSITOChanged();
        partial void OnKORZNEVKORZETChanging(System.Nullable<long> value);
        partial void OnKORZNEVKORZETChanged();
        partial void OnMIRAZONOSITOChanging(System.Nullable<long> value);
        partial void OnMIRAZONOSITOChanged();
        partial void OnMIRKOMPONENSChanging(System.Nullable<long> value);
        partial void OnMIRKOMPONENSChanged();
        partial void OnNORMAIDOChanging(System.Nullable<double> value);
        partial void OnNORMAIDOChanged();
        partial void OnKOVKANORMTEVAZONOSITOChanging(System.Nullable<long> value);
        partial void OnKOVKANORMTEVAZONOSITOChanged();
        partial void OnKOVKOPRIOAZONOSITOChanging(System.Nullable<long> value);
        partial void OnKOVKOPRIOAZONOSITOChanged();
        partial void OnCSOATMEROChanging(string value);
        partial void OnCSOATMEROChanged();
        partial void OnCSOANYAGChanging(string value);
        partial void OnCSOANYAGChanged();
        partial void OnKESZULTSEGChanging(System.Nullable<long> value);
        partial void OnKESZULTSEGChanged();
        partial void OnKOMKFORRASAZONOSITOChanging(System.Nullable<long> value);
        partial void OnKOMKFORRASAZONOSITOChanged();
        partial void OnFORRASAZONOSITOChanging(System.Nullable<long> value);
        partial void OnFORRASAZONOSITOChanged();
        partial void OnFORRASAZONOSITOTXTChanging(string value);
        partial void OnFORRASAZONOSITOTXTChanged();
        partial void OnFELVETELFELHAZONChanging(long value);
        partial void OnFELVETELFELHAZONChanged();
        partial void OnKIADASFELHAZONChanging(System.Nullable<long> value);
        partial void OnKIADASFELHAZONChanged();
        partial void OnLEZARASFELHAZONChanging(System.Nullable<long> value);
        partial void OnLEZARASFELHAZONChanged();
        partial void OnVMKIFOGASAZONOSITOChanging(System.Nullable<long> value);
        partial void OnVMKIFOGASAZONOSITOChanged();
        partial void OnINTEZKEDESAZONChanging(System.Nullable<long> value);
        partial void OnINTEZKEDESAZONChanged();
        #endregion

        public ELEMIMUNKAK()
        {
            OnCreated();
        }

    
        /// <summary>
        /// Egyedi azonosito
        /// </summary>
        [Column(Storage = "_AZONOSITO", CanBeNull = false, DbType = "NUMBER(10) NOT NULL", IsPrimaryKey = true)]
        public long AZONOSITO
        {
            get
            {
                return this._AZONOSITO;
            }
            set
            {
                if (this._AZONOSITO != value)
                {
                    this.OnAZONOSITOChanging(value);
                    this.SendPropertyChanging();
                    this._AZONOSITO = value;
                    this.SendPropertyChanged("AZONOSITO");
                    this.OnAZONOSITOChanged();
                }
            }
        }

    
        /// <summary>
        /// Tervezett kezdet idopont
        /// </summary>
        [Column(Name = @"TERVEZETT_KEZDET_IDO", Storage = "_TERVEZETTKEZDETIDO", DbType = "DATE NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> TERVEZETTKEZDETIDO
        {
            get
            {
                return this._TERVEZETTKEZDETIDO;
            }
            set
            {
                if (this._TERVEZETTKEZDETIDO != value)
                {
                    this.OnTERVEZETTKEZDETIDOChanging(value);
                    this.SendPropertyChanging();
                    this._TERVEZETTKEZDETIDO = value;
                    this.SendPropertyChanged("TERVEZETTKEZDETIDO");
                    this.OnTERVEZETTKEZDETIDOChanged();
                }
            }
        }

    
        /// <summary>
        /// Tervezett veg idopont
        /// </summary>
        [Column(Name = @"TERVEZETT_VEG_IDO", Storage = "_TERVEZETTVEGIDO", DbType = "DATE NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> TERVEZETTVEGIDO
        {
            get
            {
                return this._TERVEZETTVEGIDO;
            }
            set
            {
                if (this._TERVEZETTVEGIDO != value)
                {
                    this.OnTERVEZETTVEGIDOChanging(value);
                    this.SendPropertyChanging();
                    this._TERVEZETTVEGIDO = value;
                    this.SendPropertyChanged("TERVEZETTVEGIDO");
                    this.OnTERVEZETTVEGIDOChanged();
                }
            }
        }

    
        /// <summary>
        /// Vegrehajtas kezdet idopont
        /// </summary>
        [Column(Name = @"VEGREHAJTAS_KEZDET_IDO", Storage = "_VEGREHAJTASKEZDETIDO", DbType = "DATE NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> VEGREHAJTASKEZDETIDO
        {
            get
            {
                return this._VEGREHAJTASKEZDETIDO;
            }
            set
            {
                if (this._VEGREHAJTASKEZDETIDO != value)
                {
                    this.OnVEGREHAJTASKEZDETIDOChanging(value);
                    this.SendPropertyChanging();
                    this._VEGREHAJTASKEZDETIDO = value;
                    this.SendPropertyChanged("VEGREHAJTASKEZDETIDO");
                    this.OnVEGREHAJTASKEZDETIDOChanged();
                }
            }
        }

    
        /// <summary>
        /// Vegrehajtas veg idopont
        /// </summary>
        [Column(Name = @"VEGREHAJTAS_VEG_IDO", Storage = "_VEGREHAJTASVEGIDO", DbType = "DATE NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> VEGREHAJTASVEGIDO
        {
            get
            {
                return this._VEGREHAJTASVEGIDO;
            }
            set
            {
                if (this._VEGREHAJTASVEGIDO != value)
                {
                    this.OnVEGREHAJTASVEGIDOChanging(value);
                    this.SendPropertyChanging();
                    this._VEGREHAJTASVEGIDO = value;
                    this.SendPropertyChanged("VEGREHAJTASVEGIDO");
                    this.OnVEGREHAJTASVEGIDOChanged();
                }
            }
        }

    
        /// <summary>
        /// Felvetel idoponjta
        /// </summary>
        [Column(Name = @"FELVETEL_IDO", Storage = "_FELVETELIDO", CanBeNull = false, DbType = "DATE NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public System.DateTime FELVETELIDO
        {
            get
            {
                return this._FELVETELIDO;
            }
            set
            {
                if (this._FELVETELIDO != value)
                {
                    this.OnFELVETELIDOChanging(value);
                    this.SendPropertyChanging();
                    this._FELVETELIDO = value;
                    this.SendPropertyChanged("FELVETELIDO");
                    this.OnFELVETELIDOChanged();
                }
            }
        }

    
        /// <summary>
        /// Az az idopont, amikor kiadott lett a statusz.
        /// </summary>
        [Column(Name = @"KIADAS_IDO", Storage = "_KIADASIDO", DbType = "DATE NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> KIADASIDO
        {
            get
            {
                return this._KIADASIDO;
            }
            set
            {
                if (this._KIADASIDO != value)
                {
                    this.OnKIADASIDOChanging(value);
                    this.SendPropertyChanging();
                    this._KIADASIDO = value;
                    this.SendPropertyChanged("KIADASIDO");
                    this.OnKIADASIDOChanged();
                }
            }
        }

    
        /// <summary>
        /// Elemi munka muszaki es penzugyi zarasanak idopontja
        /// </summary>
        [Column(Name = @"LEZARAS_IDO", Storage = "_LEZARASIDO", DbType = "DATE NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> LEZARASIDO
        {
            get
            {
                return this._LEZARASIDO;
            }
            set
            {
                if (this._LEZARASIDO != value)
                {
                    this.OnLEZARASIDOChanging(value);
                    this.SendPropertyChanging();
                    this._LEZARASIDO = value;
                    this.SendPropertyChanged("LEZARASIDO");
                    this.OnLEZARASIDOChanged();
                }
            }
        }

    
        /// <summary>
        /// Aktiv regio
        /// </summary>
        [Column(Storage = "_REGIO", CanBeNull = false, DbType = "NUMBER(10) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public long REGIO
        {
            get
            {
                return this._REGIO;
            }
            set
            {
                if (this._REGIO != value)
                {
                    this.OnREGIOChanging(value);
                    this.SendPropertyChanging();
                    this._REGIO = value;
                    this.SendPropertyChanged("REGIO");
                    this.OnREGIOChanged();
                }
            }
        }

    
        /// <summary>
        /// Munka statusz
        /// </summary>
        [Column(Name = @"KOMUNKSTAT_AZONOSITO", Storage = "_KOMUNKSTATAZONOSITO", CanBeNull = false, DbType = "NUMBER(10) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public long KOMUNKSTATAZONOSITO
        {
            get
            {
                return this._KOMUNKSTATAZONOSITO;
            }
            set
            {
                if (this._KOMUNKSTATAZONOSITO != value)
                {
                    this.OnKOMUNKSTATAZONOSITOChanging(value);
                    this.SendPropertyChanging();
                    this._KOMUNKSTATAZONOSITO = value;
                    this.SendPropertyChanged("KOMUNKSTATAZONOSITO");
                    this.OnKOMUNKSTATAZONOSITOChanged();
                }
            }
        }

    
        /// <summary>
        /// Norma tevekenyseg
        /// </summary>
        [Column(Name = @"KANORMTEV_AZONOSITO", Storage = "_KANORMTEVAZONOSITO", CanBeNull = false, DbType = "NUMBER(10) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public long KANORMTEVAZONOSITO
        {
            get
            {
                return this._KANORMTEVAZONOSITO;
            }
            set
            {
                if (this._KANORMTEVAZONOSITO != value)
                {
                    this.OnKANORMTEVAZONOSITOChanging(value);
                    this.SendPropertyChanging();
                    this._KANORMTEVAZONOSITO = value;
                    this.SendPropertyChanged("KANORMTEVAZONOSITO");
                    this.OnKANORMTEVAZONOSITOChanged();
                }
            }
        }

    
        /// <summary>
        /// Megjegyzes
        /// </summary>
        [Column(Storage = "_MEGJEGYZES", DbType = "VARCHAR2(1000 CHAR) NULL", UpdateCheck = UpdateCheck.Never)]
        public string MEGJEGYZES
        {
            get
            {
                return this._MEGJEGYZES;
            }
            set
            {
                if (this._MEGJEGYZES != value)
                {
                    this.OnMEGJEGYZESChanging(value);
                    this.SendPropertyChanging();
                    this._MEGJEGYZES = value;
                    this.SendPropertyChanged("MEGJEGYZES");
                    this.OnMEGJEGYZESChanged();
                }
            }
        }

    
        /// <summary>
        /// Munka geokodja (EOV x koordinata)
        /// </summary>
        [Column(Name = @"GEOKOD_X", Storage = "_GEOKODX", DbType = "NUMBER(10,3) NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<double> GEOKODX
        {
            get
            {
                return this._GEOKODX;
            }
            set
            {
                if (this._GEOKODX != value)
                {
                    this.OnGEOKODXChanging(value);
                    this.SendPropertyChanging();
                    this._GEOKODX = value;
                    this.SendPropertyChanged("GEOKODX");
                    this.OnGEOKODXChanged();
                }
            }
        }

    
        /// <summary>
        /// Munka geokodja (EOV y koordinata)
        /// </summary>
        [Column(Name = @"GEOKOD_Y", Storage = "_GEOKODY", DbType = "NUMBER(10,3) NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<double> GEOKODY
        {
            get
            {
                return this._GEOKODY;
            }
            set
            {
                if (this._GEOKODY != value)
                {
                    this.OnGEOKODYChanging(value);
                    this.SendPropertyChanging();
                    this._GEOKODY = value;
                    this.SendPropertyChanged("GEOKODY");
                    this.OnGEOKODYChanged();
                }
            }
        }

    
        /// <summary>
        /// SAP PM muvelet azonosito
        /// </summary>
        [Column(Name = @"SAP_AZONOSITO", Storage = "_SAPAZONOSITO", DbType = "VARCHAR2(64 CHAR) NULL", UpdateCheck = UpdateCheck.Never)]
        public string SAPAZONOSITO
        {
            get
            {
                return this._SAPAZONOSITO;
            }
            set
            {
                if (this._SAPAZONOSITO != value)
                {
                    this.OnSAPAZONOSITOChanging(value);
                    this.SendPropertyChanging();
                    this._SAPAZONOSITO = value;
                    this.SendPropertyChanged("SAPAZONOSITO");
                    this.OnSAPAZONOSITOChanged();
                }
            }
        }

    
        /// <summary>
        /// Komplex munkahoz tartozo kozterulet adatok
        /// </summary>
        [Column(Name = @"KOZTADAT_AZONOSITO", Storage = "_KOZTADATAZONOSITO", DbType = "NUMBER(10) NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<long> KOZTADATAZONOSITO
        {
            get
            {
                return this._KOZTADATAZONOSITO;
            }
            set
            {
                if (this._KOZTADATAZONOSITO != value)
                {
                    this.OnKOZTADATAZONOSITOChanging(value);
                    this.SendPropertyChanging();
                    this._KOZTADATAZONOSITO = value;
                    this.SendPropertyChanged("KOZTADATAZONOSITO");
                    this.OnKOZTADATAZONOSITOChanged();
                }
            }
        }

    
        /// <summary>
        /// Komplex munka hivatkozas
        /// </summary>
        [Column(Name = @"KOMPLMUNKA_AZONOSITO", Storage = "_KOMPLMUNKAAZONOSITO", CanBeNull = false, DbType = "NUMBER(10) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public long KOMPLMUNKAAZONOSITO
        {
            get
            {
                return this._KOMPLMUNKAAZONOSITO;
            }
            set
            {
                if (this._KOMPLMUNKAAZONOSITO != value)
                {
                    this.OnKOMPLMUNKAAZONOSITOChanging(value);
                    this.SendPropertyChanging();
                    this._KOMPLMUNKAAZONOSITO = value;
                    this.SendPropertyChanged("KOMPLMUNKAAZONOSITO");
                    this.OnKOMPLMUNKAAZONOSITOChanged();
                }
            }
        }

    
        /// <summary>
        /// Display sorrend a komplex munkan belul
        /// </summary>
        [Column(Storage = "_SORSZAM", CanBeNull = false, DbType = "NUMBER(5) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public int SORSZAM
        {
            get
            {
                return this._SORSZAM;
            }
            set
            {
                if (this._SORSZAM != value)
                {
                    this.OnSORSZAMChanging(value);
                    this.SendPropertyChanging();
                    this._SORSZAM = value;
                    this.SendPropertyChanged("SORSZAM");
                    this.OnSORSZAMChanged();
                }
            }
        }

    
        /// <summary>
        /// Munka surgosseg
        /// </summary>
        [Column(Name = @"KOPRIO_AZONOSITO", Storage = "_KOPRIOAZONOSITO", CanBeNull = false, DbType = "NUMBER(10) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public long KOPRIOAZONOSITO
        {
            get
            {
                return this._KOPRIOAZONOSITO;
            }
            set
            {
                if (this._KOPRIOAZONOSITO != value)
                {
                    this.OnKOPRIOAZONOSITOChanging(value);
                    this.SendPropertyChanging();
                    this._KOPRIOAZONOSITO = value;
                    this.SendPropertyChanged("KOPRIOAZONOSITO");
                    this.OnKOPRIOAZONOSITOChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for KORZNEVKORZET in the schema.
        /// </summary>
        [Column(Name = @"KORZNEV_KORZET", Storage = "_KORZNEVKORZET", DbType = "NUMBER(10) NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<long> KORZNEVKORZET
        {
            get
            {
                return this._KORZNEVKORZET;
            }
            set
            {
                if (this._KORZNEVKORZET != value)
                {
                    this.OnKORZNEVKORZETChanging(value);
                    this.SendPropertyChanging();
                    this._KORZNEVKORZET = value;
                    this.SendPropertyChanged("KORZNEVKORZET");
                    this.OnKORZNEVKORZETChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for MIRAZONOSITO in the schema.
        /// </summary>
        [Column(Name = @"MIR_AZONOSITO", Storage = "_MIRAZONOSITO", DbType = "NUMBER(10) NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<long> MIRAZONOSITO
        {
            get
            {
                return this._MIRAZONOSITO;
            }
            set
            {
                if (this._MIRAZONOSITO != value)
                {
                    this.OnMIRAZONOSITOChanging(value);
                    this.SendPropertyChanging();
                    this._MIRAZONOSITO = value;
                    this.SendPropertyChanged("MIRAZONOSITO");
                    this.OnMIRAZONOSITOChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for MIRKOMPONENS in the schema.
        /// </summary>
        [Column(Name = @"MIR_KOMPONENS", Storage = "_MIRKOMPONENS", DbType = "NUMBER(10) NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<long> MIRKOMPONENS
        {
            get
            {
                return this._MIRKOMPONENS;
            }
            set
            {
                if (this._MIRKOMPONENS != value)
                {
                    this.OnMIRKOMPONENSChanging(value);
                    this.SendPropertyChanging();
                    this._MIRKOMPONENS = value;
                    this.SendPropertyChanged("MIRKOMPONENS");
                    this.OnMIRKOMPONENSChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for NORMAIDO in the schema.
        /// </summary>
        [Column(Storage = "_NORMAIDO", DbType = "NUMBER(10,2) NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<double> NORMAIDO
        {
            get
            {
                return this._NORMAIDO;
            }
            set
            {
                if (this._NORMAIDO != value)
                {
                    this.OnNORMAIDOChanging(value);
                    this.SendPropertyChanging();
                    this._NORMAIDO = value;
                    this.SendPropertyChanged("NORMAIDO");
                    this.OnNORMAIDOChanged();
                }
            }
        }

    
        /// <summary>
        /// Kovetkezonek javasolt elemi munka normatevekenysege
        /// </summary>
        [Column(Name = @"KOV_KANORMTEV_AZONOSITO", Storage = "_KOVKANORMTEVAZONOSITO", DbType = "NUMBER(10) NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<long> KOVKANORMTEVAZONOSITO
        {
            get
            {
                return this._KOVKANORMTEVAZONOSITO;
            }
            set
            {
                if (this._KOVKANORMTEVAZONOSITO != value)
                {
                    this.OnKOVKANORMTEVAZONOSITOChanging(value);
                    this.SendPropertyChanging();
                    this._KOVKANORMTEVAZONOSITO = value;
                    this.SendPropertyChanged("KOVKANORMTEVAZONOSITO");
                    this.OnKOVKANORMTEVAZONOSITOChanged();
                }
            }
        }

    
        /// <summary>
        /// Kovetkezonek javasolt elemi munka surgossege
        /// </summary>
        [Column(Name = @"KOV_KOPRIO_AZONOSITO", Storage = "_KOVKOPRIOAZONOSITO", DbType = "NUMBER(10) NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<long> KOVKOPRIOAZONOSITO
        {
            get
            {
                return this._KOVKOPRIOAZONOSITO;
            }
            set
            {
                if (this._KOVKOPRIOAZONOSITO != value)
                {
                    this.OnKOVKOPRIOAZONOSITOChanging(value);
                    this.SendPropertyChanging();
                    this._KOVKOPRIOAZONOSITO = value;
                    this.SendPropertyChanged("KOVKOPRIOAZONOSITO");
                    this.OnKOVKOPRIOAZONOSITOChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for CSOATMERO in the schema.
        /// </summary>
        [Column(Storage = "_CSOATMERO", DbType = "VARCHAR2(64 CHAR) NULL", UpdateCheck = UpdateCheck.Never)]
        public string CSOATMERO
        {
            get
            {
                return this._CSOATMERO;
            }
            set
            {
                if (this._CSOATMERO != value)
                {
                    this.OnCSOATMEROChanging(value);
                    this.SendPropertyChanging();
                    this._CSOATMERO = value;
                    this.SendPropertyChanged("CSOATMERO");
                    this.OnCSOATMEROChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for CSOANYAG in the schema.
        /// </summary>
        [Column(Storage = "_CSOANYAG", DbType = "VARCHAR2(64 CHAR) NULL", UpdateCheck = UpdateCheck.Never)]
        public string CSOANYAG
        {
            get
            {
                return this._CSOANYAG;
            }
            set
            {
                if (this._CSOANYAG != value)
                {
                    this.OnCSOANYAGChanging(value);
                    this.SendPropertyChanging();
                    this._CSOANYAG = value;
                    this.SendPropertyChanged("CSOANYAG");
                    this.OnCSOANYAGChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for KESZULTSEG in the schema.
        /// </summary>
        [Column(Storage = "_KESZULTSEG", DbType = "NUMBER(10) NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<long> KESZULTSEG
        {
            get
            {
                return this._KESZULTSEG;
            }
            set
            {
                if (this._KESZULTSEG != value)
                {
                    this.OnKESZULTSEGChanging(value);
                    this.SendPropertyChanging();
                    this._KESZULTSEG = value;
                    this.SendPropertyChanged("KESZULTSEG");
                    this.OnKESZULTSEGChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for KOMKFORRASAZONOSITO in the schema.
        /// </summary>
        [Column(Name = @"KOMKFORRAS_AZONOSITO", Storage = "_KOMKFORRASAZONOSITO", DbType = "NUMBER(10) NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<long> KOMKFORRASAZONOSITO
        {
            get
            {
                return this._KOMKFORRASAZONOSITO;
            }
            set
            {
                if (this._KOMKFORRASAZONOSITO != value)
                {
                    this.OnKOMKFORRASAZONOSITOChanging(value);
                    this.SendPropertyChanging();
                    this._KOMKFORRASAZONOSITO = value;
                    this.SendPropertyChanged("KOMKFORRASAZONOSITO");
                    this.OnKOMKFORRASAZONOSITOChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for FORRASAZONOSITO in the schema.
        /// </summary>
        [Column(Name = @"FORRAS_AZONOSITO", Storage = "_FORRASAZONOSITO", DbType = "NUMBER(10) NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<long> FORRASAZONOSITO
        {
            get
            {
                return this._FORRASAZONOSITO;
            }
            set
            {
                if (this._FORRASAZONOSITO != value)
                {
                    this.OnFORRASAZONOSITOChanging(value);
                    this.SendPropertyChanging();
                    this._FORRASAZONOSITO = value;
                    this.SendPropertyChanged("FORRASAZONOSITO");
                    this.OnFORRASAZONOSITOChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for FORRASAZONOSITOTXT in the schema.
        /// </summary>
        [Column(Name = @"FORRAS_AZONOSITO_TXT", Storage = "_FORRASAZONOSITOTXT", DbType = "VARCHAR2(64 CHAR) NULL", UpdateCheck = UpdateCheck.Never)]
        public string FORRASAZONOSITOTXT
        {
            get
            {
                return this._FORRASAZONOSITOTXT;
            }
            set
            {
                if (this._FORRASAZONOSITOTXT != value)
                {
                    this.OnFORRASAZONOSITOTXTChanging(value);
                    this.SendPropertyChanging();
                    this._FORRASAZONOSITOTXT = value;
                    this.SendPropertyChanged("FORRASAZONOSITOTXT");
                    this.OnFORRASAZONOSITOTXTChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for FELVETELFELHAZON in the schema.
        /// </summary>
        [Column(Name = @"FELVETEL_FELH_AZON", Storage = "_FELVETELFELHAZON", CanBeNull = false, DbType = "NUMBER(10) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public long FELVETELFELHAZON
        {
            get
            {
                return this._FELVETELFELHAZON;
            }
            set
            {
                if (this._FELVETELFELHAZON != value)
                {
                    this.OnFELVETELFELHAZONChanging(value);
                    this.SendPropertyChanging();
                    this._FELVETELFELHAZON = value;
                    this.SendPropertyChanged("FELVETELFELHAZON");
                    this.OnFELVETELFELHAZONChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for KIADASFELHAZON in the schema.
        /// </summary>
        [Column(Name = @"KIADAS_FELH_AZON", Storage = "_KIADASFELHAZON", DbType = "NUMBER(10) NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<long> KIADASFELHAZON
        {
            get
            {
                return this._KIADASFELHAZON;
            }
            set
            {
                if (this._KIADASFELHAZON != value)
                {
                    this.OnKIADASFELHAZONChanging(value);
                    this.SendPropertyChanging();
                    this._KIADASFELHAZON = value;
                    this.SendPropertyChanged("KIADASFELHAZON");
                    this.OnKIADASFELHAZONChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for LEZARASFELHAZON in the schema.
        /// </summary>
        [Column(Name = @"LEZARAS_FELH_AZON", Storage = "_LEZARASFELHAZON", DbType = "NUMBER(10) NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<long> LEZARASFELHAZON
        {
            get
            {
                return this._LEZARASFELHAZON;
            }
            set
            {
                if (this._LEZARASFELHAZON != value)
                {
                    this.OnLEZARASFELHAZONChanging(value);
                    this.SendPropertyChanging();
                    this._LEZARASFELHAZON = value;
                    this.SendPropertyChanged("LEZARASFELHAZON");
                    this.OnLEZARASFELHAZONChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for VMKIFOGASAZONOSITO in the schema.
        /// </summary>
        [Column(Name = @"VM_KIFOGAS_AZONOSITO", Storage = "_VMKIFOGASAZONOSITO", DbType = "NUMBER(10) NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<long> VMKIFOGASAZONOSITO
        {
            get
            {
                return this._VMKIFOGASAZONOSITO;
            }
            set
            {
                if (this._VMKIFOGASAZONOSITO != value)
                {
                    this.OnVMKIFOGASAZONOSITOChanging(value);
                    this.SendPropertyChanging();
                    this._VMKIFOGASAZONOSITO = value;
                    this.SendPropertyChanged("VMKIFOGASAZONOSITO");
                    this.OnVMKIFOGASAZONOSITOChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for INTEZKEDESAZON in the schema.
        /// </summary>
        [Column(Name = @"INTEZKEDES_AZON", Storage = "_INTEZKEDESAZON", DbType = "NUMBER(10) NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<long> INTEZKEDESAZON
        {
            get
            {
                return this._INTEZKEDESAZON;
            }
            set
            {
                if (this._INTEZKEDESAZON != value)
                {
                    this.OnINTEZKEDESAZONChanging(value);
                    this.SendPropertyChanging();
                    this._INTEZKEDESAZON = value;
                    this.SendPropertyChanged("INTEZKEDESAZON");
                    this.OnINTEZKEDESAZONChanged();
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    /// <summary>
    /// There are no comments for MIRTUSZContext.VELEMIMUNKAINMLIST in the schema.
    /// </summary>
    [Table(Name = @"MIRTUSZ.V_ELEMI_MUNKA_IN_M_LIST")]
    public partial class VELEMIMUNKAINMLIST : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private long _AZONOSITO;

        private string _MAIN;

        private string _KESZULTSEG;

        private string _PRIORITAS;

        private string _IDO;

        private string _BEJSZ;

        private string _MUNKASZAM;

        private string _CIM;

        private string _STARTIDO;

        private long _KOMPLEXMUNKAAZONOSITO;

        private int _SORSZAM;

        private long _STATUSZ;

        private System.Nullable<System.DateTime> _TERVEZETTKEZDETIDO;

        private System.Nullable<System.DateTime> _TERVEZETTVEGIDO;

        private System.Nullable<System.DateTime> _VEGREHAJTASKEZDETIDO;

        private System.Nullable<System.DateTime> _VEGREHAJTASVEGIDO;

        private long _KANORMTEVAZONOSITO;

        private System.Nullable<long> _KOVKOPRIOAZONOSITO;

        private string _KOVKANORMTEVMEGNEVEZES;

        private string _KOVKOPRIOMEGNEVEZES;

        private System.Nullable<System.DateTime> _MUNKAKEZDES;

        private System.Nullable<System.DateTime> _MUNKABEFEJEZES;

        private System.Nullable<System.DateTime> _OSYSDATE;

        private string _MAINICON;

        private string _ICON0;

        private string _ICON1;
        #pragma warning restore 0649
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnAZONOSITOChanging(long value);
        partial void OnAZONOSITOChanged();
        partial void OnMAINChanging(string value);
        partial void OnMAINChanged();
        partial void OnKESZULTSEGChanging(string value);
        partial void OnKESZULTSEGChanged();
        partial void OnPRIORITASChanging(string value);
        partial void OnPRIORITASChanged();
        partial void OnIDOChanging(string value);
        partial void OnIDOChanged();
        partial void OnBEJSZChanging(string value);
        partial void OnBEJSZChanged();
        partial void OnMUNKASZAMChanging(string value);
        partial void OnMUNKASZAMChanged();
        partial void OnCIMChanging(string value);
        partial void OnCIMChanged();
        partial void OnSTARTIDOChanging(string value);
        partial void OnSTARTIDOChanged();
        partial void OnKOMPLEXMUNKAAZONOSITOChanging(long value);
        partial void OnKOMPLEXMUNKAAZONOSITOChanged();
        partial void OnSORSZAMChanging(int value);
        partial void OnSORSZAMChanged();
        partial void OnSTATUSZChanging(long value);
        partial void OnSTATUSZChanged();
        partial void OnTERVEZETTKEZDETIDOChanging(System.Nullable<System.DateTime> value);
        partial void OnTERVEZETTKEZDETIDOChanged();
        partial void OnTERVEZETTVEGIDOChanging(System.Nullable<System.DateTime> value);
        partial void OnTERVEZETTVEGIDOChanged();
        partial void OnVEGREHAJTASKEZDETIDOChanging(System.Nullable<System.DateTime> value);
        partial void OnVEGREHAJTASKEZDETIDOChanged();
        partial void OnVEGREHAJTASVEGIDOChanging(System.Nullable<System.DateTime> value);
        partial void OnVEGREHAJTASVEGIDOChanged();
        partial void OnKANORMTEVAZONOSITOChanging(long value);
        partial void OnKANORMTEVAZONOSITOChanged();
        partial void OnKOVKOPRIOAZONOSITOChanging(System.Nullable<long> value);
        partial void OnKOVKOPRIOAZONOSITOChanged();
        partial void OnKOVKANORMTEVMEGNEVEZESChanging(string value);
        partial void OnKOVKANORMTEVMEGNEVEZESChanged();
        partial void OnKOVKOPRIOMEGNEVEZESChanging(string value);
        partial void OnKOVKOPRIOMEGNEVEZESChanged();
        partial void OnMUNKAKEZDESChanging(System.Nullable<System.DateTime> value);
        partial void OnMUNKAKEZDESChanged();
        partial void OnMUNKABEFEJEZESChanging(System.Nullable<System.DateTime> value);
        partial void OnMUNKABEFEJEZESChanged();
        partial void OnOSYSDATEChanging(System.Nullable<System.DateTime> value);
        partial void OnOSYSDATEChanged();
        partial void OnMAINICONChanging(string value);
        partial void OnMAINICONChanged();
        partial void OnICON0Changing(string value);
        partial void OnICON0Changed();
        partial void OnICON1Changing(string value);
        partial void OnICON1Changed();
        #endregion

        public VELEMIMUNKAINMLIST()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for AZONOSITO in the schema.
        /// </summary>
        [Key]
        [Column(Storage = "_AZONOSITO", CanBeNull = false, DbType = "NUMBER(10) NOT NULL", IsPrimaryKey = true)]
        public long AZONOSITO
        {
            get
            {
                return this._AZONOSITO;
            }
            set
            {
                if (this._AZONOSITO != value)
                {
                    this.OnAZONOSITOChanging(value);
                    this.SendPropertyChanging();
                    this._AZONOSITO = value;
                    this.SendPropertyChanged("AZONOSITO");
                    this.OnAZONOSITOChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for MAIN in the schema.
        /// </summary>
        [Column(Storage = "_MAIN", CanBeNull = false, DbType = "VARCHAR2(64 CHAR) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string MAIN
        {
            get
            {
                return this._MAIN;
            }
            set
            {
                if (this._MAIN != value)
                {
                    this.OnMAINChanging(value);
                    this.SendPropertyChanging();
                    this._MAIN = value;
                    this.SendPropertyChanged("MAIN");
                    this.OnMAINChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for KESZULTSEG in the schema.
        /// </summary>
        [Column(Storage = "_KESZULTSEG", DbType = "VARCHAR2(4000 CHAR) NULL", UpdateCheck = UpdateCheck.Never)]
        public string KESZULTSEG
        {
            get
            {
                return this._KESZULTSEG;
            }
            set
            {
                if (this._KESZULTSEG != value)
                {
                    this.OnKESZULTSEGChanging(value);
                    this.SendPropertyChanging();
                    this._KESZULTSEG = value;
                    this.SendPropertyChanged("KESZULTSEG");
                    this.OnKESZULTSEGChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for PRIORITAS in the schema.
        /// </summary>
        [Column(Storage = "_PRIORITAS", DbType = "VARCHAR2(64 CHAR) NULL", UpdateCheck = UpdateCheck.Never)]
        public string PRIORITAS
        {
            get
            {
                return this._PRIORITAS;
            }
            set
            {
                if (this._PRIORITAS != value)
                {
                    this.OnPRIORITASChanging(value);
                    this.SendPropertyChanging();
                    this._PRIORITAS = value;
                    this.SendPropertyChanged("PRIORITAS");
                    this.OnPRIORITASChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for IDO in the schema.
        /// </summary>
        [Column(Storage = "_IDO", DbType = "VARCHAR2(4000 CHAR) NULL", UpdateCheck = UpdateCheck.Never)]
        public string IDO
        {
            get
            {
                return this._IDO;
            }
            set
            {
                if (this._IDO != value)
                {
                    this.OnIDOChanging(value);
                    this.SendPropertyChanging();
                    this._IDO = value;
                    this.SendPropertyChanged("IDO");
                    this.OnIDOChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for BEJSZ in the schema.
        /// </summary>
        [Column(Storage = "_BEJSZ", DbType = "VARCHAR2(4000 CHAR) NULL", UpdateCheck = UpdateCheck.Never)]
        public string BEJSZ
        {
            get
            {
                return this._BEJSZ;
            }
            set
            {
                if (this._BEJSZ != value)
                {
                    this.OnBEJSZChanging(value);
                    this.SendPropertyChanging();
                    this._BEJSZ = value;
                    this.SendPropertyChanged("BEJSZ");
                    this.OnBEJSZChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for MUNKASZAM in the schema.
        /// </summary>
        [Column(Storage = "_MUNKASZAM", DbType = "VARCHAR2(4000 CHAR) NULL", UpdateCheck = UpdateCheck.Never)]
        public string MUNKASZAM
        {
            get
            {
                return this._MUNKASZAM;
            }
            set
            {
                if (this._MUNKASZAM != value)
                {
                    this.OnMUNKASZAMChanging(value);
                    this.SendPropertyChanging();
                    this._MUNKASZAM = value;
                    this.SendPropertyChanged("MUNKASZAM");
                    this.OnMUNKASZAMChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for CIM in the schema.
        /// </summary>
        [Column(Storage = "_CIM", DbType = "VARCHAR2(114 CHAR) NULL", UpdateCheck = UpdateCheck.Never)]
        public string CIM
        {
            get
            {
                return this._CIM;
            }
            set
            {
                if (this._CIM != value)
                {
                    this.OnCIMChanging(value);
                    this.SendPropertyChanging();
                    this._CIM = value;
                    this.SendPropertyChanged("CIM");
                    this.OnCIMChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for STARTIDO in the schema.
        /// </summary>
        [Column(Name = @"START_IDO", Storage = "_STARTIDO", DbType = "VARCHAR2(16 CHAR) NULL", UpdateCheck = UpdateCheck.Never)]
        public string STARTIDO
        {
            get
            {
                return this._STARTIDO;
            }
            set
            {
                if (this._STARTIDO != value)
                {
                    this.OnSTARTIDOChanging(value);
                    this.SendPropertyChanging();
                    this._STARTIDO = value;
                    this.SendPropertyChanged("STARTIDO");
                    this.OnSTARTIDOChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for KOMPLEXMUNKAAZONOSITO in the schema.
        /// </summary>
        [Column(Name = @"KOMPLEX_MUNKA_AZONOSITO", Storage = "_KOMPLEXMUNKAAZONOSITO", CanBeNull = false, DbType = "NUMBER(10) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public long KOMPLEXMUNKAAZONOSITO
        {
            get
            {
                return this._KOMPLEXMUNKAAZONOSITO;
            }
            set
            {
                if (this._KOMPLEXMUNKAAZONOSITO != value)
                {
                    this.OnKOMPLEXMUNKAAZONOSITOChanging(value);
                    this.SendPropertyChanging();
                    this._KOMPLEXMUNKAAZONOSITO = value;
                    this.SendPropertyChanged("KOMPLEXMUNKAAZONOSITO");
                    this.OnKOMPLEXMUNKAAZONOSITOChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for SORSZAM in the schema.
        /// </summary>
        [Column(Storage = "_SORSZAM", CanBeNull = false, DbType = "NUMBER(5) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public int SORSZAM
        {
            get
            {
                return this._SORSZAM;
            }
            set
            {
                if (this._SORSZAM != value)
                {
                    this.OnSORSZAMChanging(value);
                    this.SendPropertyChanging();
                    this._SORSZAM = value;
                    this.SendPropertyChanged("SORSZAM");
                    this.OnSORSZAMChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for STATUSZ in the schema.
        /// </summary>
        [Column(Storage = "_STATUSZ", CanBeNull = false, DbType = "NUMBER(10) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public long STATUSZ
        {
            get
            {
                return this._STATUSZ;
            }
            set
            {
                if (this._STATUSZ != value)
                {
                    this.OnSTATUSZChanging(value);
                    this.SendPropertyChanging();
                    this._STATUSZ = value;
                    this.SendPropertyChanged("STATUSZ");
                    this.OnSTATUSZChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for TERVEZETTKEZDETIDO in the schema.
        /// </summary>
        [Column(Name = @"TERVEZETT_KEZDET_IDO", Storage = "_TERVEZETTKEZDETIDO", DbType = "DATE NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> TERVEZETTKEZDETIDO
        {
            get
            {
                return this._TERVEZETTKEZDETIDO;
            }
            set
            {
                if (this._TERVEZETTKEZDETIDO != value)
                {
                    this.OnTERVEZETTKEZDETIDOChanging(value);
                    this.SendPropertyChanging();
                    this._TERVEZETTKEZDETIDO = value;
                    this.SendPropertyChanged("TERVEZETTKEZDETIDO");
                    this.OnTERVEZETTKEZDETIDOChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for TERVEZETTVEGIDO in the schema.
        /// </summary>
        [Column(Name = @"TERVEZETT_VEG_IDO", Storage = "_TERVEZETTVEGIDO", DbType = "DATE NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> TERVEZETTVEGIDO
        {
            get
            {
                return this._TERVEZETTVEGIDO;
            }
            set
            {
                if (this._TERVEZETTVEGIDO != value)
                {
                    this.OnTERVEZETTVEGIDOChanging(value);
                    this.SendPropertyChanging();
                    this._TERVEZETTVEGIDO = value;
                    this.SendPropertyChanged("TERVEZETTVEGIDO");
                    this.OnTERVEZETTVEGIDOChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for VEGREHAJTASKEZDETIDO in the schema.
        /// </summary>
        [Column(Name = @"VEGREHAJTAS_KEZDET_IDO", Storage = "_VEGREHAJTASKEZDETIDO", DbType = "DATE NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> VEGREHAJTASKEZDETIDO
        {
            get
            {
                return this._VEGREHAJTASKEZDETIDO;
            }
            set
            {
                if (this._VEGREHAJTASKEZDETIDO != value)
                {
                    this.OnVEGREHAJTASKEZDETIDOChanging(value);
                    this.SendPropertyChanging();
                    this._VEGREHAJTASKEZDETIDO = value;
                    this.SendPropertyChanged("VEGREHAJTASKEZDETIDO");
                    this.OnVEGREHAJTASKEZDETIDOChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for VEGREHAJTASVEGIDO in the schema.
        /// </summary>
        [Column(Name = @"VEGREHAJTAS_VEG_IDO", Storage = "_VEGREHAJTASVEGIDO", DbType = "DATE NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> VEGREHAJTASVEGIDO
        {
            get
            {
                return this._VEGREHAJTASVEGIDO;
            }
            set
            {
                if (this._VEGREHAJTASVEGIDO != value)
                {
                    this.OnVEGREHAJTASVEGIDOChanging(value);
                    this.SendPropertyChanging();
                    this._VEGREHAJTASVEGIDO = value;
                    this.SendPropertyChanged("VEGREHAJTASVEGIDO");
                    this.OnVEGREHAJTASVEGIDOChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for KANORMTEVAZONOSITO in the schema.
        /// </summary>
        [Column(Name = @"KANORMTEV_AZONOSITO", Storage = "_KANORMTEVAZONOSITO", CanBeNull = false, DbType = "NUMBER(10) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public long KANORMTEVAZONOSITO
        {
            get
            {
                return this._KANORMTEVAZONOSITO;
            }
            set
            {
                if (this._KANORMTEVAZONOSITO != value)
                {
                    this.OnKANORMTEVAZONOSITOChanging(value);
                    this.SendPropertyChanging();
                    this._KANORMTEVAZONOSITO = value;
                    this.SendPropertyChanged("KANORMTEVAZONOSITO");
                    this.OnKANORMTEVAZONOSITOChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for KOVKOPRIOAZONOSITO in the schema.
        /// </summary>
        [Column(Name = @"KOV_KOPRIO_AZONOSITO", Storage = "_KOVKOPRIOAZONOSITO", DbType = "NUMBER(10) NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<long> KOVKOPRIOAZONOSITO
        {
            get
            {
                return this._KOVKOPRIOAZONOSITO;
            }
            set
            {
                if (this._KOVKOPRIOAZONOSITO != value)
                {
                    this.OnKOVKOPRIOAZONOSITOChanging(value);
                    this.SendPropertyChanging();
                    this._KOVKOPRIOAZONOSITO = value;
                    this.SendPropertyChanged("KOVKOPRIOAZONOSITO");
                    this.OnKOVKOPRIOAZONOSITOChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for KOVKANORMTEVMEGNEVEZES in the schema.
        /// </summary>
        [Column(Name = @"KOV_KANORMTEV_MEGNEVEZES", Storage = "_KOVKANORMTEVMEGNEVEZES", DbType = "VARCHAR2(64 CHAR) NULL", UpdateCheck = UpdateCheck.Never)]
        public string KOVKANORMTEVMEGNEVEZES
        {
            get
            {
                return this._KOVKANORMTEVMEGNEVEZES;
            }
            set
            {
                if (this._KOVKANORMTEVMEGNEVEZES != value)
                {
                    this.OnKOVKANORMTEVMEGNEVEZESChanging(value);
                    this.SendPropertyChanging();
                    this._KOVKANORMTEVMEGNEVEZES = value;
                    this.SendPropertyChanged("KOVKANORMTEVMEGNEVEZES");
                    this.OnKOVKANORMTEVMEGNEVEZESChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for KOVKOPRIOMEGNEVEZES in the schema.
        /// </summary>
        [Column(Name = @"KOV_KOPRIO_MEGNEVEZES", Storage = "_KOVKOPRIOMEGNEVEZES", DbType = "VARCHAR2(64 CHAR) NULL", UpdateCheck = UpdateCheck.Never)]
        public string KOVKOPRIOMEGNEVEZES
        {
            get
            {
                return this._KOVKOPRIOMEGNEVEZES;
            }
            set
            {
                if (this._KOVKOPRIOMEGNEVEZES != value)
                {
                    this.OnKOVKOPRIOMEGNEVEZESChanging(value);
                    this.SendPropertyChanging();
                    this._KOVKOPRIOMEGNEVEZES = value;
                    this.SendPropertyChanged("KOVKOPRIOMEGNEVEZES");
                    this.OnKOVKOPRIOMEGNEVEZESChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for MUNKAKEZDES in the schema.
        /// </summary>
        [Column(Storage = "_MUNKAKEZDES", DbType = "DATE NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> MUNKAKEZDES
        {
            get
            {
                return this._MUNKAKEZDES;
            }
            set
            {
                if (this._MUNKAKEZDES != value)
                {
                    this.OnMUNKAKEZDESChanging(value);
                    this.SendPropertyChanging();
                    this._MUNKAKEZDES = value;
                    this.SendPropertyChanged("MUNKAKEZDES");
                    this.OnMUNKAKEZDESChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for MUNKABEFEJEZES in the schema.
        /// </summary>
        [Column(Storage = "_MUNKABEFEJEZES", DbType = "DATE NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> MUNKABEFEJEZES
        {
            get
            {
                return this._MUNKABEFEJEZES;
            }
            set
            {
                if (this._MUNKABEFEJEZES != value)
                {
                    this.OnMUNKABEFEJEZESChanging(value);
                    this.SendPropertyChanging();
                    this._MUNKABEFEJEZES = value;
                    this.SendPropertyChanged("MUNKABEFEJEZES");
                    this.OnMUNKABEFEJEZESChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for OSYSDATE in the schema.
        /// </summary>
        [Column(Storage = "_OSYSDATE", DbType = "DATE NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> OSYSDATE
        {
            get
            {
                return this._OSYSDATE;
            }
            set
            {
                if (this._OSYSDATE != value)
                {
                    this.OnOSYSDATEChanging(value);
                    this.SendPropertyChanging();
                    this._OSYSDATE = value;
                    this.SendPropertyChanged("OSYSDATE");
                    this.OnOSYSDATEChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for MAINICON in the schema.
        /// </summary>
        [Column(Name = @"MAIN_ICON", Storage = "_MAINICON", CanBeNull = false, DbType = "VARCHAR2(60 CHAR) NULL", UpdateCheck = UpdateCheck.Never)]
        public string MAINICON
        {
            get
            {
                return this._MAINICON;
            }
            set
            {
                if (this._MAINICON != value)
                {
                    this.OnMAINICONChanging(value);
                    this.SendPropertyChanging();
                    this._MAINICON = value;
                    this.SendPropertyChanged("MAINICON");
                    this.OnMAINICONChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for ICON0 in the schema.
        /// </summary>
        [Column(Storage = "_ICON0", DbType = "VARCHAR2(17 CHAR) NULL", UpdateCheck = UpdateCheck.Never)]
        public string ICON0
        {
            get
            {
                return this._ICON0;
            }
            set
            {
                if (this._ICON0 != value)
                {
                    this.OnICON0Changing(value);
                    this.SendPropertyChanging();
                    this._ICON0 = value;
                    this.SendPropertyChanged("ICON0");
                    this.OnICON0Changed();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for ICON1 in the schema.
        /// </summary>
        [Column(Storage = "_ICON1", DbType = "CHAR(14) NULL", UpdateCheck = UpdateCheck.Never)]
        public string ICON1
        {
            get
            {
                return this._ICON1;
            }
            set
            {
                if (this._ICON1 != value)
                {
                    this.OnICON1Changing(value);
                    this.SendPropertyChanging();
                    this._ICON1 = value;
                    this.SendPropertyChanged("ICON1");
                    this.OnICON1Changed();
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }

        public static IEnumerable<VELEMIMUNKAINMLIST> GetPage(ODataQueryOptions<VELEMIMUNKAINMLIST> queryOptions)
        {
            using (MIRTUSZContext.MIRTUSZDataContext mirtuszDC = new MIRTUSZContext.MIRTUSZDataContext())
            {
                mirtuszDC.Connection.Open();
                if (queryOptions.Filter != null)
                {
                    return (IEnumerable<VELEMIMUNKAINMLIST>)queryOptions.ApplyTo(mirtuszDC.VELEMIMUNKAINMLIST).GetEnumerator();

                    //db.TimelineItems.Where(tl => tl.ProductID == SelectedPID).Select(tl => new TimelineItem { Description = tl.Description, Title = tl.Title }).AsEnumerable<TimelineItem>();
                }

                return mirtuszDC.VELEMIMUNKAINMLIST.Skip(queryOptions.Skip == null ? 0 : queryOptions.Skip.Value).Take(queryOptions.Top.Value).Select(dbe => new VELEMIMUNKAINMLIST()
                {
                    AZONOSITO = dbe.AZONOSITO,
                    CIM = dbe.CIM,
                    MAIN = dbe.MAIN,
                    KESZULTSEG = dbe.KESZULTSEG,
                    PRIORITAS = dbe.PRIORITAS
                });
                //return a;
            }
        }
    }

}
